# spring.profiles.active にデフォルトでアクティブとなるプロファイルを指定
spring:
  profiles:
    active: dev

# `---`でプロファイルを区切る
# プロファイル名は spring.profiles に書く
# 開発用
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    driverClassName: org.postgresql.Driver
    username: appusr
    password: appusr
    maxActive: 15
    maxIdle: 10
    minIdle: 5
    initialSize: 0
logging.file: spring-boot.log

# 本番用
---
spring:
  profiles: production
  datasource:
    url: 
    driverClassName: org.postgresql.Driver
    username: 
    password: 
    maxActive: 15
    maxIdle: 10
    minIdle: 5
    initialSize: 0
logging.file: spring-boot.log
    
# `java -jar -Dspring.profiles.active=production hoge.jar`